// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// ✅ دالة موحدة لقراءة المتغيرات من أي مصدر
function getEnv(key: string): string | undefined {
  // 1. Vite client-side
  try {
    const viteEnv = import.meta.env as Record<string, string | undefined>;
    if (viteEnv?.[key]) return viteEnv[key];
  } catch {}
  
  // 2. Node.js SSR
  if (typeof process !== 'undefined' && process.env?.[key]) {
    return process.env[key];
  }
  
  // 3. Global fallback
  if (typeof globalThis !== 'undefined' && (globalThis as any)[key]) {
    return (globalThis as any)[key];
  }
  
  return undefined;
}

function createSupabaseClient() {
  // ✅ Vercel يضع المتغيرات كـ VITE_* في import.meta.env وقت البناء
  // ✅ وفي SSR runtime تكون متاحة عبر process.env (لأنها تُسرّب)
  const SUPABASE_URL = 
    getEnv('VITE_SUPABASE_URL') ||
    getEnv('SUPABASE_URL');

  const SUPABASE_PUBLISHABLE_KEY = 
    getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
    getEnv('VITE_SUPABASE_ANON_KEY') ||
    getEnv('SUPABASE_PUBLISHABLE_KEY') ||
    getEnv('SUPABASE_ANON_KEY');

  // ✅ Log تشخيصي
  console.log('[Supabase] Env check:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlPrefix: SUPABASE_URL?.substring(0, 30),
    keyPrefix: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20),
    availableEnvKeys: typeof process !== 'undefined' 
      ? Object.keys(process.env).filter(k => k.includes('SUPABASE'))
      : 'no-process',
  });

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY'] : []),
    ];
    const message = `[Supabase] Missing env variables: ${missing.join(', ')}`;
    console.error(message);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// ✅ Lazy proxy - لا ينشئ client حتى يُستدعى فعلاً
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    try {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    } catch (error) {
      console.error('[Supabase] Failed to create client:', error);
      throw error;
    }
  },
});